### ISSUE TITLE
Sections with comments should stay visible

### ISSUE THREAD

**Issue by jonwgeorge** [ouija-io/ouija#26]
This could be optional, but I'd like to see the icons remain visible when a section has comments. Instead of showing up when moused over.

**Comment by byosko** [comment]
Maybe a simple configuration option? @mattcreager @colinmacdonald

**Comment by colinmacdonald** [comment]
Makes sense to me as an option.

**Comment by mattcreager** [comment]
We actually did have this feature, the sass still includes it... I may have forgotten to implement it during the move to React :) Woops.

**Comment by GoOz** [comment]
+1 on this :)
