### ISSUE TITLE
Authentication button invisible but clickable when Ouija is closed

### ISSUE THREAD

**Issue by jonwgeorge** [ouija-io/ouija#33]
The "Sign in with Twitter" button is invisible but clickable when Ouija is closed and there are zero comments on that section.

Not sure if this is just because I'm using custom CSS to make Ouija work with my theme, but to duplicate:
- [visit this post on my blog](http://www.jonwgeorge.com/what-is-open-source-and-why-should-you-care/)
- go to the second paragraph starting with "Open-source doesn't just matter..."
- hover over the Ouija button, then move your mouse in a straight line down.

You'll see the link <code>https://auth.goinstant.net/begin?account=jonwgeorge&app=ouija&returnTo=http%3A%2F%2Fwww.jonwgeorge.com%2Fwhat-is-open-source-and-why-should-you-care%2F&providerName=twitter</code> but will be unable to actually see the button.

This works on any <code><p></code> element without a previous comment.

**Comment by colinmacdonald** [comment]
@ntassone I see this happening on casper with only default styles too. Can we `display: none` when the comments are not visible to prevent this?

**Comment by ntassone** [comment]
Yeah, `visibility: hidden` will probably work better and not interfere with the transition like `display: none` would. Or maybe pushing the z-index down. Will test and make a PR.
