### ISSUE TITLE
Pass ouija options as an object

### ISSUE THREAD

**Issue by colinmacdonald** [ouija-io/ouija#36]
Ouija options are building up fast:

```
ouija_identifier
ouija_connect_url
ouija_article_content
ouija_section_elements
ouija_hide_controls // soon
```

Should be able to set these options as an object instead of individual vars on the window.

**Comment by jonwgeorge** [comment]
Would it not be easier to do this instead?

<pre>
var Options = {"array":[
    {"identifier": ""},
    {"connect_url": ""},
    {"article_content": ""},
    {"section_elements": ""},
    {"hide_controls": ""}
]};
</pre>

**Comment by halfdan** [comment]
@jonwgeorge Not like that.

More like: 

```
new Ouija({
  identifier: 12,
  connect_url: 'url',
  article_content: '.article_class',
  section_elements: '.section_elements',
  hide_controls: true
});
```

**Comment by jonwgeorge** [comment]
@halfdan Yeah, that looks better. I suck at Javascript haha.

**Comment by jonwgeorge** [comment]
Also, now that you guys have added the ability to comment on images, which is a nice feature, how do I go about disabling it? No need to comment on images for me at least.

**Comment by colinmacdonald** [comment]
@jonwgeorge Using the section elements option: `window.ouija_section_elements = 'p, ol';`. The default is: `'p, ol, :has(img)'`
