### ISSUE TITLE
Ouija loading on pages since v0.1.2

### ISSUE THREAD

**Issue by jonwgeorge** [ouija-io/ouija#37]
Looks like after switching to using <code>v0.1.2</code> Ouija is now loading on pages as well as posts. I don't remember this happening before, and it's more likely an issue with Ghost and handlebars if anything.

**Comment by halfdan** [comment]
Example?

**Comment by jonwgeorge** [comment]
@halfdan I'm using a custom theme, so that's likely the cause: http://www.jonwgeorge.com/about/

**Comment by halfdan** [comment]
That is technically not a bug with Ouija nor Ghost. You have a static page which essentially is just a post that doesn’t appear in the normal post list. If you want to prevent Ouija from showing up you’d need to adjust the snippet from Ouija:

```
{{#with post}}
{{unless page}}
... Ouija code ..
{{/unless}}
{{/with}}
```

**Comment by jonwgeorge** [comment]
I didn't realize that was available in Ghost (or handlebars). Guess I didn't read the docs that far.

**Comment by jonwgeorge** [comment]
Actually, it seems that doesn't work.
![screen shot 2014-05-05 at 4 59 34 pm](https://cloud.githubusercontent.com/assets/2319568/2883823/a04b17ac-d4a0-11e3-8ae5-bf2f2a89f4d7.png)

**Comment by halfdan** [comment]
Oops. That’s supposed to read `{{#unless ..}}`

**Comment by jonwgeorge** [comment]
<s>That causes Ouija not to load at all.</s>

Nevermind. I misspelled page...

**Comment by colinmacdonald** [comment]
@jonwgeorge Can I close this as a non-issue then?

**Comment by jonwgeorge** [comment]
Yep. Just fat fingers on my end haha.
