### ISSUE TITLE
Can't Clone

### ISSUE THREAD

**Issue by HoddzDJ** [ouija-io/ouija#44]
Hey guys.

I'm pretty new to all this GitHub stuff and the like. I think I have done it right, but I can't seem to b able to clone the repo.

Here is my output from Terminal...

```
bens-mbp:Ghost benhodder$ git clone git@github.com:goinstant/ouija.git ouija
Cloning into 'ouija'...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I am running Mac OS X 10.9.3.

Regards, Ben Hodder.

**Comment by halfdan** [comment]
@HoddzDJ You need to use the https URL (`https://github.com/goinstant/ouija.git`). Using the one you used only works when you have push access to the repository.

Note that for just using Ouija you don't need to clone the repository.

**Comment by HoddzDJ** [comment]
@halfdan Managed to get it cloned, and moved it into content/apps/ouija. Added the stylesheet and other bit to the default.hbs but it doesn't seem to change anything at all.

Am I missing something?

**Comment by halfdan** [comment]
@HoddzDJ As I said - you don't need to clone the repository if you only want to use it. Follow the setup guide: https://github.com/goinstant/ouija#quick-install

**Comment by HoddzDJ** [comment]
@halfdan So I just add those two bits of code to the default.hbs and away I go? If that's right, it doesn't work like it does on the Ouija Demo blog...

**Comment by halfdan** [comment]
Did you restart Ghost? Link? There's not enough information to help you here.

**Comment by HoddzDJ** [comment]
@halfdan I did restart Ghost, I'm running it locally to start with to see if I can get it going.

**Comment by HoddzDJ** [comment]
@halfdan I'm running a custom theme, if that makes any difference?

**Comment by HoddzDJ** [comment]
@halfdan Surely the `{{#with post}}` code block should be in `post.hbs` and not `default.hbs`?

**Comment by colinmacdonald** [comment]
@hoddzDJ Have you tried the `window.ouija_article_content` option? https://github.com/goinstant/ouija#how-to-configure-ouija

The default selector is `.post-content`. If your theme does not have this class you will need to tell Ouija which element is your post content's parent.

If I had access to your theme I could debug it further.

**Comment by HoddzDJ** [comment]
@colinmacdonald My theme is just an edited version of Casper. I will upload a copy of it shortly. I have however decided to try on my live site: http://hoddzdj.com

**Comment by colinmacdonald** [comment]
`GET http://hoddzdj.com/assets/css/ouija.css/?v=030ec8a99f 404 (Not Found)`
`GET http://hoddzdj.com/assets/js/ouija.js/?v=030ec8a99f 404 (Not Found)`

Did you build ouija after cloning it?

**Comment by HoddzDJ** [comment]
@colinmacdonald Was told I didn't need to clone it :-/

**Comment by halfdan** [comment]
Well you don't, but you don't have the correct script tags in there.

**Comment by HoddzDJ** [comment]
@halfdan Cheers...

**Comment by HoddzDJ** [comment]
@colinmacdonald @halfdan Didn't realise the quick start and developer had different codes in...

**Comment by colinmacdonald** [comment]
No worries! Are you up and running now?

**Comment by HoddzDJ** [comment]
@colinmacdonald I think I am, yeah. Just need to remove Disqus.

**Comment by rk-panchal** [comment]
hello
 plz give me any solution 
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by javorszky** [comment]
Hi @rk-panchal,

There seems to be an issue with how you set up git on your computer. Follow these guides: https://help.github.com/articles/generating-ssh-keys/

**Comment by rk-panchal** [comment]
Hi @javorszky
 i want to deploy a application on heroku .  i get url app after heroku create but when i run config command there is one issue , i found there is different url so that i am not able to run.....git heroku master.

**Comment by javorszky** [comment]
@rk-panchal, you need to take that up with heroku support. https://devcenter.heroku.com/articles/keys

**Comment by rk-panchal** [comment]
@javorszky
 thnks dear...i will try

**Comment by macbroadcast** [comment]
git clone https://github.com/ouija-io/ouija.git works perfect for me

**Comment by rk-panchal** [comment]
@hi
i want to go for facebook authentication....but i find email......error.
plz help me....

On Fri, May 15, 2015 at 4:46 PM, Marc Manthey notifications@github.com
wrote:

> git clone https://github.com/ouija-io/ouija.git works perfect for me
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ouija-io/ouija/issues/44#issuecomment-102372505.

## 

Thanks & Regards
Ravinder Kumar <panchal17101989@gmail.com <aniltimt@gmail.com>>
Mobile No- 07357981156

**Comment by ghost** [comment]
@halfdan  thanks ,ur solution is working for me....
