### ISSUE TITLE
Ouija shows commenting form when loading

### ISSUE THREAD

**Issue by halfdan** [ouija-io/ouija#46]
Ouija seems to show the commenting form when clicking on the loading symbol before it has finished loading: 

![ouija-loading](https://cloud.githubusercontent.com/assets/176576/2918812/69d2c338-d6d4-11e3-81f7-cf41f7ee276e.gif)

**Note:** Bug shows at the end - had to CMD+R/clear content on that to make it show up.

**Comment by colinmacdonald** [comment]
Solution to this is to use the promise that gets resolved here: https://github.com/goinstant/ouija/blob/master/app/post.js#L57 in the `handleControlsClick` listener here: https://github.com/goinstant/ouija/blob/master/app/ouija.jsx#L130

It would delay opening the conversation block until the comments have been fetched.
