### ISSUE TITLE
Add colophon

### ISSUE THREAD

**Issue by ntassone** [ouija-io/ouija#47]
Show a "Powered by [Ouija](http://ouija.io)" message at the bottom of the Ouija drawer.

**Comment by ntassone** [comment]
![image](https://cloud.githubusercontent.com/assets/1572205/2919985/684bd04c-d6e1-11e3-9f6f-7b2eb556a87e.png)

**Comment by halfdan** [comment]
Looks great! (Ouija should prevent empty comments though)

**Comment by ntassone** [comment]
@halfdan Thanks! It does, those are just leftover from previous testing.
