### ISSUE TITLE
The all Ouija block is selected after hitting submit button

### ISSUE THREAD

**Issue by GoOz** [ouija-io/ouija#48]
Gifs speaks the truth.

![](https://dl.dropboxusercontent.com/u/6801063/ouija.mov.gif)

See what i mean?

I need to focus elsewhere which closes Ouija or focus in the textarea to unselect.

**Comment by colinmacdonald** [comment]
This bug doesn't exist in Chrome, only firefox and safari.

**Comment by GoOz** [comment]
Yeah sorry, forgot to specify.
