### ISSUE TITLE
Comments Database location

### ISSUE THREAD

**Issue by GoOz** [ouija-io/ouija#60]
Guys, i wanted to clean up a little bit my tests and delete some comments i did but i couldn't find where those comments are stored.
Could you point me the location please?

**Comment by colinmacdonald** [comment]
You can do this from the Data Inspector in the GoInstant dashboard: https://goinstant.com/dashboard

Find the app, hover over the cog wheel, then click Data Inspector. You will have access to all the comments for a blog post room by room.

For example, below you can see I'm in room `post_1` and my comments are organized by section. If I click the trash can next to `id-145b8c5c3fd-000` I will remove that comment. You can expand those comment IDs to see the content and the user Id.

![screenshot 2014-05-13 10 07 00](https://cloud.githubusercontent.com/assets/3648226/2957422/7dd8618e-da9f-11e3-8abe-640121b10783.png)

Note: we are currently investigating a bug with the data inspector where you are prevented from deleting keys with some custom ACLs. If you run into this issue simply revert your ACL back to the default for removing the comments. When you are finished be sure to reapply the Ouija ACL.

Default ACL:

```
{
  "$room": {
    "#join": {
      "users": [
        "*"
      ]
    },
    "#visible": {
      "users": [
        "*"
      ]
    },
    "#rooms": {
      "users": [
        "*"
      ]
    },
    "#all": {
      "users": [
        "*"
      ]
    },
    ".users": {
      "$userId": {
        "#write": {
          "users": [
            "$userId"
          ],
          "groups": []
        },
        "#read": {
          "users": [
            "*"
          ]
        },
        "email": {
          "#write": {},
          "#read": {
            "users": [
              "$userId"
            ],
            "groups": []
          }
        },
        "id": {
          "#all": {},
          "#get": {
            "users": [
              "*"
            ]
          }
        },
        "groups": {
          "#all": {},
          "#get": {
            "users": [
              "*"
            ]
          }
        },
        "provider": {
          "#all": {},
          "#get": {
            "users": [
              "*"
            ]
          }
        }
      }
    }
  },
  "#connect": {
    "users": [
      "*"
    ]
  }
}
```

**Comment by GoOz** [comment]
Oh ok. So basically, there's no local database like the Ghost one. Is this temporary or do you plan to keep it that way ?
To be honest, the main reason i'm not convinced by Disqus and such is because the comments are not stored on my own server (and also because you need to create an account to comment)

**Comment by colinmacdonald** [comment]
Ouija will continue to use GoInstant as its data store.

Even though the comments are stored in GoInstant and not your local database, you still have complete control over that data. This is one of the fundamental differences between Ouija and a service like Disqus.

**Comment by GoOz** [comment]
I just don't like to depend on some other platform… i hope you can understand why i'm not so thrilled about that.
But i'll give a try. I'll be damned before i use FB, G+, Disqus anyway :D
Could you just tell me then if you plan on adding a comment list/moderation page directly in ghost admin if the next Ghost releases allow it ? Because that'll be great, not that GoInstant's Data Inspector is not user-friendly but… yes it isn't. :P

**Comment by colinmacdonald** [comment]
Comment moderation is on our roadmap, but we don't have a timeline yet. This will happen once the Ghost apps API is ready. See the Q2 section of Ghost's roadmap [here](https://github.com/tryghost/Ghost/wiki/Roadmap#est-q2-2014)

**Comment by GoOz** [comment]
Yeah that's what i thought too. :) Thanks for the answers.
