### ISSUE TITLE
Mobile Comments

### ISSUE THREAD

**Issue by HoddzDJ** [ouija-io/ouija#61]
Hey guys,

Ghost is majorly a mobile blog. With this in mind, I was wondering if there were any plans for adding comments via mobile/tablet? I appreciate it could be difficult what with touch-screens being picked up differently than a mouse hover.

It's the only thing stopping this being pretty darn amazing!

**Comment by halfdan** [comment]
@HoddzDJ Yes - this is planned. See https://github.com/goinstant/ouija/issues/8

Please use issue search before posting a new issue.

**Comment by HoddzDJ** [comment]
@halfdan I did a search of the closed issues, didn't find anything. Sorry.
