### ISSUE TITLE
Lack of indication to scroll for more comments to see

### ISSUE THREAD

**Issue by GoOz** [ouija-io/ouija#64]
When you have a lot of comments, you need to scroll down to see the hidden ones because of the Ouija's fixed height.
That's fine but it needs to have some indication because the scrollbar is not visible by default (OSX's browser only i guess).
See.
![](https://dl.dropboxusercontent.com/u/6801063/ouija_comments.mov.gif)

**Comment by colinmacdonald** [comment]
Agreed.

**Comment by ntassone** [comment]
+1. I've been experimenting with some options for this. Tricky part is making sure the overflow indicator can work on all kinds of themes.

**Comment by friksa** [comment]
+1

Maybe a vertical fade when there is an overflow.  This is an example of something that fades horizontally.  http://jsfiddle.net/Ff9JL/

**Comment by ntassone** [comment]
@friksa Thanks for the link, this is something I've considered before for this issue. The problem with using a gradient is that it won't adapt to darker themes. We can use a scss variable to make it easier for those using the custom dev setup but the quick plug and play on darker themes will have a glaring white gradient. 

The webkit mask on the other hand is pretty awesome, though obviously not very well supported :(

**Comment by GoOz** [comment]
A SVG mask works pretty well and is well supported too… if you forget about IE :) 
[See an example here](http://tutorials.jenkov.com/svg/mask.html)

**Comment by friksa** [comment]
Since you have scrollbars in IE, it should be ok.  The real issue is on the Mac where scroll bars are invisible until you actually scroll.
