### ISSUE TITLE
Ouija self hosted - The Independence Day Issue

### ISSUE THREAD

**Issue by mattcreager** [ouija-io/ouija#71]
![image](https://cloud.githubusercontent.com/assets/1623992/3644353/7117f042-10df-11e4-880c-dd00158208d0.png)

**Comment by Graloth** [comment]
Might want to state more clearly what this issue is about, I had no idea until you linked to it in my previous issue about GoInstant's closure.

**Comment by jonwgeorge** [comment]
I don't know if you guys have used Firebase before, I've used it once it a previous project. I could fork Ouija and see if I can get it running in firebase.. If not, here's the link: https://www.firebase.com

**Comment by klamping** [comment]
I second use of Firebase for this. I've used it in the past and it's pretty nice.

**Comment by ahdinosaur** [comment]
-1 for Firebase, as it defeats the possibility of Ouija being self-hosted, which would be really really awesome.

**Comment by halfdan** [comment]
Hi everyone,
the plan is to have the backend configurable. There will be an API specification on how Ouija will handle data. This will make it possible to have different server backend, including firebase.

**Comment by franklouwers** [comment]
Any updates on how to run it selfhosted?

**Comment by mattcreager** [comment]
@franklouwers soon, I'm in the process of picking my life up and shipping it to SF, that's been all consuming!  What's I settle in, this is next up :)

**Comment by macbroadcast** [comment]
Hope your shipping to SF went fine, does soon mean before christmas ? :dancers:

**Comment by laughingman-hass** [comment]
Hi just wondering, is there anything that can be used in the mean time for a new deployment? I've never used ouija before, or goinstant.

**Comment by macbroadcast** [comment]
ouija is just a ghost intergration with some additional realtime features, sure you can use it without goinstant, pay for it on ghost.org or download and install it by yourself https://github.com/TryGhost/Ghost  cheers

**Comment by laughingman-hass** [comment]
@macbroadcast I am already using ghost (its about a day old) http://hass-isnull.io/, was just wondering if ouija can be used without goinstant on ghost as a commenting solution.

**Comment by macbroadcast** [comment]
@hass-isnull only if you help me rebuild the API :heart_eyes:

**Comment by macbroadcast** [comment]
@hass-isnull Why not simply integrate disqus, when you just want a commenting function ? :stuck_out_tongue_closed_eyes: https://help.disqus.com/customer/portal/articles/1454924-ghost-installation-instructions

**Comment by laughingman-hass** [comment]
@macbroadcast I can try to help :smile:  I work alot more on Ruby and Java but I have time....
for now :wink:

**Comment by laughingman-hass** [comment]
@macbroadcast I like the idea ouija brings with inline commenting. A lot of people have told me stay from Disqus for one reason or another
What else can ouija do other than commenting?

**Comment by fiddur** [comment]
When ouija didn't work, and not wanting to use Disqus (with ads and whatnot), I wrote a new free commenting system.  It's very rought still, but you can try it out: http://fredrik.liljegren.org/introducing-some-comments/

**Comment by HLFH** [comment]
It seems that NodeBB for Ghost is the best stable solution at the moment. https://github.com/psychobunny/nodebb-plugin-blog-comments
