### ISSUE TITLE
Will Ouija continue to be developed and supported after closure of GoInstant?

### ISSUE THREAD

**Issue by Graloth** [ouija-io/ouija#72]
Ouija requires GoInstant to function as far as I can understand, but GoInstant will discontinue on August the 31st, Ouija is a project from GoInstant.

Will Ouija continue to get supported and developed after GoInstant is closed?
Would like to know about this, as it is the main reason why I am not switching to it yet, people are also asking about it on the Ghost forums

**Comment by mattcreager** [comment]
Yes!  I have no intention of abandoning Ouija, this just increases the urgency of #71!

**Comment by mattcreager** [comment]
Probably worth a read: https://ghost.org/forum/plugins/14667-author-annotations-plugin-much-needed-if-not-already-existent/9/

**Comment by halfdan** [comment]
The repository has now moved to its own organisation on Github. I'm going to close this issue as development can now continue without GoInstant.
