### ISSUE TITLE
Add responsive styling / mobile experience

### ISSUE THREAD

**Issue by ntassone** [ouija-io/ouija#8]
Comments are not yet optimized for mobile use.

**Comment by hkalant** [comment]
That's true. It ruins my blog's responsive layout. You can't expect from a preview version to be fully optimized for mobile devices though. They are just at the beginning. Take a look: http://ghost.hkalant.bitnamiapp.com/

**Comment by ntassone** [comment]
Hey Harry, I'm a collaborator on the project :)

This issue is more of a todo than an issue. 
—
